services:
  - type: web
    name: codeforge-ide
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html